UR5_movegroup_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
   
  gains:
    shoulder_pan_joint:
      p: 4000
      d: 200
      i: 1
      i_clamp: 1
    shoulder_lift_joint:
      p: 10000
      d: 200
      i: 1
      i_clamp: 1
    elbow_joint:
      p: 2000
      d: 20
      i: 1
      i_clamp: 1
    wrist_1_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    wrist_2_joint:
      p: 500
      d: 1
      i: 1
      i_clamp: 1
    wrist_3_joint:
      p: 10
      d: 0.1
      i: 0
      i_clamp: 1
   
Robotiq_movegroup_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
    - finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1

# # Simulation settings for using moveit_sim_controllers
# moveit_sim_hw_interface:
#   joint_model_group: UR5_movegroup
#   joint_model_group_pose: URUP
# # Settings for ros_control_boilerplate control loop
# generic_hw_control_loop:
#   loop_hz: 300
#   cycle_time_error_threshold: 0.01
# # Settings for ros_control hardware interface
# hardware_interface:
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#     - finger_joint
#   sim_control_mode: 1  # 0: position, 1: velocity
# # Publish all joint states
# # Creates the /joint_states topic necessary in ROS
# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50
# controller_list:
#   - name: UR5_movegroup_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - shoulder_pan_joint
#       - shoulder_lift_joint
#       - elbow_joint
#       - wrist_1_joint
#       - wrist_2_joint
#       - wrist_3_joint
#   - name: Robotiq_movegroup_controller
#     action_ns: follow_joint_trajectory
#     default: True
#     type: FollowJointTrajectory
#     joints:
#       - finger_joint
# UR5_movegroup_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gains:
#     shoulder_pan_joint:
#       p: 1000
#       d: 50
#       i: 10
#       i_clamp: 100
#     shoulder_lift_joint:
#       p: 5000
#       d: 30
#       i: 100
#       i_clamp: 400
#     elbow_joint:
#       p: 5000
#       d: 50
#       i: 10
#       i_clamp: 100
#     wrist_1_joint:
#       p: 200
#       d: 20
#       i: 10
#       i_clamp: 100
#     wrist_2_joint:
#       p: 100
#       d: 10
#       i: 0.1
#       i_clamp: 100
#     wrist_3_joint:
#       p: 10
#       d: 1
#       i: 0.1
#       i_clamp: 100
# Robotiq_movegroup_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - finger_joint
#   gains:
#     finger_joint:
#       p: 40
#       d: 0
#       i: 0
#       i_clamp: 1


# UR5_movegroup_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gains:
#     shoulder_pan_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     shoulder_lift_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     elbow_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_1_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_2_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
#     wrist_3_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1
# Robotiq_movegroup_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#     - finger_joint
#   gains:
#     finger_joint:
#       p: 100
#       d: 1
#       i: 1
#       i_clamp: 1